### ISSUE TITLE
Get Failed

### ISSUE THREAD

**Issue by lalawuu** [sajith/cs-papers#1]
When git annex get, It alway failed to connect.

**Comment by sajith** [comment]
Thanks for the notice!  I'm on it.

**Comment by sajith** [comment]
I think this should be fixed now -- looks like I'd forgotten to push stuff to Github.  Could you please try again?  Try doing a `git pull` and then `git annex get .` -- that should work.

Merely out of curiosity, what is your interest in my little repository?  I'm pretty sure all these papers are publicly available elsewhere in the Internet as well.  I'm just collecting things that interest me at random points of time. :-)

**Comment by MarisaKirisame** [comment]
It's just because, why pull thing one by one when you can pull them off in a batch?
Also it is a nice index of cs papers, so it also work as a suggestions of what to read...

**Comment by sajith** [comment]
Oh, okay.  That is nice to know. :-) 

Is the repository working for you now?

**Comment by MarisaKirisame** [comment]
Yep, all is well.

**Comment by sajith** [comment]
Great, thank you!
