### ISSUE TITLE
git annex get fail with 99 failure

### ISSUE THREAD

**Issue by MarisaKirisame** [sajith/cs-papers#2]
get A Call-by-name Lambda-calculus Machine - Jean-Louis Krivine.pdf
  Remote origin not usable by git-annex; setting annex-ignore
(not available)
  No other repository is known to contain the file.
failed

I got 99 failure and git is one

**Comment by sajith** [comment]
I'm on it.  Looks like this is a duplicate of #1 -- could you please try again and update that issue?

**Comment by MarisaKirisame** [comment]
It is a duplicate. I just cannot resist making a 99 pun...
